services:
  - type: web
    name: b3-pro-3

    runtime: python

    buildCommand: pip install -r requirements.txt

    startCommand: gunicorn app:app

    envVars:
      - key: BOT_TOKEN
        sync: false
